Generate documentation for copyWith and toJson
rrousselGit/freezed pull request #1069
Opened 2024-04-12 20:33 UTC by rekire

Resolves #1068

I tried to minimize the changes. This PR also corrects the position of the `@override` for some cases where the override was above the documentation.

2024-04-16 12:46 UTC, rekire commented
@rrousselGit I noticed that you merged a dependabot PR, so you are working today. Is there anything in my PR I should change?

2024-05-14 10:34 UTC, rrousselGit commented on packages/freezed/lib/src/templates/copy_with.dart
> +    return '''
Sounds like _maybeOverride should have an optional `doc` parameter. Otherwise LGTM

2024-05-14 10:48 UTC, rrousselGit requested changes
There appear to be a few missing places with regards to copyWith documentation.

We need to document the `call` method of the object returned by `get copyWith`.
This will provide doc when writing `copyWith(...)`.
Currently docs appear with `.copyWith`, but not `.copyWiht(...)`

We also will want doc for deep copy, such as `value.copyWith.field(...)`

2024-07-08 05:55 UTC, rrousselGit commented
Do you still wish to work on this?

2024-07-08 06:02 UTC, rekire commented
To be honest I totally forgot about this PR. I need to check my PR to find out what changes are still required. Might be someone else would be quicker, but I want to finish what I have started. Thank you for the reminder.

2024-07-08 15:27 UTC, rekire commented
@rrousselGit did I catch all the missing parts? The last time I checked the generated code everything was documented. I am not sure why I missed those.

2024-07-09 04:58 UTC, rrousselGit commented
It sounds good. Do you mind refactoring the doc into a getter on `data`? So that we don't have multiple duplicates of the same doc in the source.

2024-07-09 05:14 UTC, rekire commented
@rrousselGit done

2024-07-09 07:22 UTC, rrousselGit commented on packages/freezed/lib/src/templates/copy_with.dart
> +  }
```suggestion
  String _copyWithDocs(String name) {
    return '''
/// Create a copy of $name
/// with the given fields replaced by the non-null parameter values.''';
  }
```

2024-07-09 07:22 UTC, rrousselGit commented on packages/freezed/lib/src/templates/copy_with.dart
> +${_generateDataDocs(data.name)}
```suggestion
${_copyWithDocs(data.name)}
```

2024-07-09 07:23 UTC, rrousselGit commented on packages/freezed/lib/src/templates/copy_with.dart
> +${_generateDataDocs(data.name)}
```suggestion
${_copyWithDocs(data.name)}
```

2024-07-09 07:23 UTC, rrousselGit commented on packages/freezed/lib/src/templates/copy_with.dart
> +${_generateDataDocs(data.name, indent: '  ')}
```suggestion
${_copyWithDocs(data.name)}
```

2024-07-09 07:23 UTC, rrousselGit commented on packages/freezed/lib/src/templates/copy_with.dart
> +${_generateDataDocs(data.name, indent: '  ')}
```suggestion
${_copyWithDocs(data.name)}
```

2024-07-09 07:23 UTC, rrousselGit commented on packages/freezed/lib/src/templates/copy_with.dart
> +${_generateDataDocs(data.name)}
```suggestion
${_copyWithDocs(data.name)}
```

2024-07-09 07:27 UTC, rrousselGit approved these changes

2024-07-09 07:33 UTC, merged

2025-05-15 13:31 UTC, rekire commented
This looks like a bug of my PR or by a change made after this PR. So or so please create a new issue for that. This PR was merged in summer last year.